version: '3'
services:
  http-server:
    container_name: dev-http-server
    image: nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./http-server/nginx.config:/etc/nginx/conf.d/default.conf
      - ./web-client/app/static:/srv/static

  web-client:
    container_name: dev-web-client
    build: ./web-client
    volumes:
      - ./web-client/app/static:/srv/app/static
    command: tail -f /dev/null

  app-server:
    container_name: dev-app-server
    build: ./app-server
    environment:
      - FLASK_APP=/srv/app/wsgi.py
      - FLASK_DEBUG=1
      # - FLASK_DEBUG=0
    restart: always
    volumes:
      - ./app-server/app:/srv/app
    working_dir: /srv/app
    command: flask run --host=0.0.0.0 --port=5000
    # command: gunicorn wsgi:app --chdir /srv/app -b 0.0.0.0:5000

  database:
    container_name: dev-database
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=sandbox
      - POSTGRES_USER=sandbox
      - POSTGRES_DB=sandbox
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data
